import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "./globals.css";

import { Header } from "@/components/header";
import { QueryProviders } from "@/shared/providers/query-providers";
import { Footer } from "@/components/footer";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${outfit.className} antialiased`}>
        <QueryProviders>
          <div>
            <Header />
            {children}
            <Footer />
          </div>
        </QueryProviders>
      </body>
    </html>
  );
}
